- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "car_cmd_vel"
  gz_topic_name: "/model/simple_car/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/R1/cmd_vel"
  gz_topic_name: "/model/R1/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

  direction: ROS_TO_GZ

- ros_topic_name: "/R2/cmd_vel"
  gz_topic_name: "/model/R2/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# Individual Wheel Control
- ros_topic_name: "/R2/front_left_wheel/cmd_vel"
  gz_topic_name: "/model/R2/joint/front_left_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/R2/front_right_wheel/cmd_vel"
  gz_topic_name: "/model/R2/joint/front_right_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/R2/mid_left_wheel/cmd_vel"
  gz_topic_name: "/model/R2/joint/mid_left_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/R2/mid_right_wheel/cmd_vel"
  gz_topic_name: "/model/R2/joint/mid_right_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/R2/back_left_wheel/cmd_vel"
  gz_topic_name: "/model/R2/joint/back_left_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/R2/back_right_wheel/cmd_vel"
  gz_topic_name: "/model/R2/joint/back_right_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
